// TODO: Make this outputs.tf file generated by the terratest code and only run in tests, 
// or use GCP cloud secrets, push the secret and then retrieve it
output test {
  value = local.service_config_with_connections
  sensitive = true
}